TrajectoryPlannerROS:
  max_vel_x: 10
  min_vel_x: 0.1
  max_steer_angle : 0.5
  min_steer_angle : -0.5
  max_vel_theta: 0.5
  min_in_place_vel_theta: 0.2
  wheel_radius : 0.1016
  wheel_distance : 0.508

  acc_lim_theta: 2
  acc_lim_x: 0.5
  acc_lim_y: 0.5
  backup_vel : -1
  holonomic_robot: false

  yaw_goal_tolerance: 1.0
  xy_goal_tolerance: 0.4
  meter_scoring: true
