obstacle_range: 2.5
raytrace_range: 2.0

footprint: [[-0.10, 0.19],[-0.10, -0.19], [0.10, -0.19], [0.10, 0.19]]

inflation_radius: 0.2

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: base_laser,
  data_type: LaserScan, topic: /scan, marking: true,
  clearing: true, max_obstacle_height: 20.0, min_obstacle_height: 0.0}
